stages:
  - setup
  - setup
  - test

setup:
  image: node:latest
  stage: setup
  script:
    - npm install

test:
  image: node:latest
  stage: test
  script:
    - npm run test -- --coverage
  only:
    - merge_requests
    - main
    - develop
