image: node:14

stages:
  - install
  - build
  - test

before_script:
  - npm install -g expo-cli

install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - echo "Running tests"
    - npm test
