image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker-compose up -d

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker-compose run --rm expo npm install

test:
  stage: test
  script:
    - docker-compose run --rm expo npm test
