image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache python3 py3-pip
  - pip3 install --upgrade pip setuptools wheel
  - pip3 install docker-compose

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose run --rm app pytest
