stages:
  - install
  - build
  - test
  - deploy

install:
  stage: install
  script:
    - npm install -g expo-cli
    - expo --version
    - npm ci

build:
  stage: build
  script:
    - npx expo export:web

test:
  stage: test
  script:
    - echo "Running tests"
    # Adicione seus comandos de teste aqui, por exemplo:
    # - npm test

deploy:
  stage: deploy
  script:
    - echo "Deploying to the server"
    # Adicione seus comandos de deploy aqui, por exemplo:
    # - scp -r web-build/ user@server:/path/to/deploy
  only:
    - main

