image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - apk update
  - apk add --no-cache docker-compose

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Listing files in current directory"
    - ls -al
    - echo "Listing files in root directory"
    - ls -al /
    - echo "Changing to the correct directory"
    - cd /builds/diana-global/diana-wallet
    - ls -al
    - docker-compose up -d
    - docker-compose exec expo npm install

test:
  stage: test
  script:
    - docker-compose exec expo npm test
