image: node:14

stages:
  - install
  - build
  - test

before_script:
  - npm install -g expo-cli
  - expo --version

install:
  stage: install
  script:
    - npm ci
    - ls -la node_modules

build:
  stage: build
  script:
    - echo "Building project"
    - npm run build

test:
  stage: test
  script:
    - echo "Running tests"
    - npm test
