image: node:14

services:
  - docker:dind

variables:
  DOCKER_DRIVER: vfs
  DOCKER_TLS_CERTDIR: ""
  EXPO_TOKEN: $EXPO_TOKEN

stages:
  - test
  - build

before_script:
  # Instalar Docker CLI no Debian
  - apt-get update
  - apt-get install -y docker.io
  # Iniciar o daemon do Docker com driver vfs
  - dockerd --storage-driver=vfs --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 & sleep 10
  - docker info

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm ci
    - npm test

build:
  stage: build
  script:
    - npm ci
    - npm install -g expo-cli
    - expo build:android --non-interactive --no-wait --type apk
  artifacts:
    paths:
      - ./dist
