image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - apk update
  - apk add --no-cache docker-compose

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker-compose up -d
    - docker-compose run --rm expo npm install

test:
  stage: test
  script:
    - docker-compose run --rm expo npm test
